recipes:
    global:
        - applications::git
        - applications::wget
        - applications::pwgen
        - applications::xmlstarlet
        - applications::pv
        - applications::htop
        - dotfiles::gitconfig
        - applications::grunt-cli
        - applications::git-flow
        - applications::siege
        - applications::nodejs
        - applications::ssh_config
        - dotfiles::vim
        - applications::composer
    mac_os_x:
        - applications::1password
        - applications::dropbox
        - applications::evernote
        - applications::istatmenus4
        - applications::omnigraffle
        - applications::things
        - applications::vlc
        - applications::alfred
        - applications::totalfinder
        - applications::bash-completion
        - dotfiles::bash_it
        - dotfiles::inputrc
        - applications::imageoptim
        - applications::imagealpha
        - applications::svgo
        - applications::sublime_text_3
        - applications::codekit
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
attributes:
    git:
        name: Kumar Vora
        email: vorakumar@gmail.com
    osxdefaults:
        computername: anayak
    dotfiles:
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
